### PR TITLE
0.1.3 *Breaking changes* Moved env into env package & more

### PR DESCRIPTION
**Pull request by MichaelS11**
0.1.3 *Breaking changes*
Moved env into env package
Moved package vars into env
Added import into vm
Simplified packages
Moved packages testing into vm

### CODE REVIEW

**Comment by MichaelS11** [comment]
@mattn Please review and merge

**Comment by MichaelS11** [comment]
@mattn Any thoughts?

**Comment by MichaelS11** [comment]
@mattn ?

**Comment by mattn** [comment]
Sorry. Thank you.

**Pull request merged**
