### PR TITLE
0.0.8 - Added runInfo, StmtsStmt, and more tests

### PR DESCRIPTION
**Pull request by MichaelS11**
Version changed to 0.0.6

### CODE REVIEW

**Comment by MichaelS11** [comment]
@mattn 

I know this is a big PR, my apologies. I did tried to split it up at first but was having a difficult time doing so.

This PR creates runInfo so all the functions can be called with that, so only the pointer is copied instead of all the passed variables. It should help reuse some variables so not as many are being created.

Also did a cleanup of what looked like lots of unneeded/unused code.

I also think the runInfo format can add other advantages as well later one. For example being able to pass the runInfo and using it for return data which would make lots of the code easier to use/understand.

Could you restart Travis, I think it was just a Travis bug, not an issue with the PR.

**Comment by mattn** [comment]
We forgot to update version variable but next version should be 0.0.8. :)

**Comment by MichaelS11** [comment]
Looking at Go 1.10.x it passed the first two times but got stuck the third time. It is weird that it is getting stuck in the same spot. I am not sure what is going on but the way it is acting makes me think it is something with Travis and Go. Not sure how to troubleshoot the issue.

**Comment by mattn** [comment]
I'm trying this using go1.8 on my local server. Test always hang at TestAnk.

```
warning: no packages being tested depend on github.com/mattn/anko/ast/astutil
=== RUN   TestRunNonInteractiveFile
ReadFile error: open /tmp/go18/gopath/src/github.com/mattn/anko/core/testdata/not-found.ank: no such file or directory
Execute error: syntax error
--- PASS: TestRunNonInteractiveFile (0.00s)
=== RUN   TestRunNonInteractiveExecute
Execute error: invalid operation
--- PASS: TestRunNonInteractiveExecute (0.00s)
=== RUN   TestRunInteractive
--- PASS: TestRunInteractive (0.08s)
PASS
coverage: 14.7% of statements in github.com/mattn/anko, github.com/mattn/anko/ast/astutil, github.com/mattn/anko/vm, github.com/mattn/anko/core, github.com/mattn/anko/packages
ok  	github.com/mattn/anko	0.098s
warning: no packages being tested depend on github.com/mattn/anko
warning: no packages being tested depend on github.com/mattn/anko/vm
warning: no packages being tested depend on github.com/mattn/anko/core
warning: no packages being tested depend on github.com/mattn/anko/packages
=== RUN   TestWalk
--- PASS: TestWalk (0.00s)
=== RUN   TestBadCode
--- PASS: TestBadCode (0.00s)
PASS
coverage: 5.8% of statements in github.com/mattn/anko, github.com/mattn/anko/ast/astutil, github.com/mattn/anko/vm, github.com/mattn/anko/core, github.com/mattn/anko/packages
ok  	github.com/mattn/anko/ast/astutil	0.024s
warning: no packages being tested depend on github.com/mattn/anko
warning: no packages being tested depend on github.com/mattn/anko/ast/astutil
warning: no packages being tested depend on github.com/mattn/anko/core
warning: no packages being tested depend on github.com/mattn/anko/packages
=== RUN   TestExecuteError
--- PASS: TestExecuteError (0.00s)
=== RUN   TestSetError
--- PASS: TestSetError (0.00s)
=== RUN   TestAddrError
--- PASS: TestAddrError (0.00s)
=== RUN   TestDefineAndGet
--- PASS: TestDefineAndGet (0.00s)
=== RUN   TestDefineModify
--- PASS: TestDefineModify (0.00s)
=== RUN   TestDefineType
--- PASS: TestDefineType (0.00s)
=== RUN   TestDefineTypeFail
--- PASS: TestDefineTypeFail (0.00s)
=== RUN   TestAddr
--- PASS: TestAddr (0.00s)
=== RUN   TestDelete
--- PASS: TestDelete (0.00s)
=== RUN   TestDeleteGlobal
--- PASS: TestDeleteGlobal (0.00s)
=== RUN   TestAddPackage
--- PASS: TestAddPackage (0.00s)
=== RUN   TestExternalResolverValueAndGet
--- PASS: TestExternalResolverValueAndGet (0.00s)
=== RUN   TestExternalResolverTypeAndGet
--- PASS: TestExternalResolverTypeAndGet (0.00s)
=== RUN   TestExternalResolverAddr
--- PASS: TestExternalResolverAddr (0.00s)
=== RUN   TestRaceCreateSameVariable
--- PASS: TestRaceCreateSameVariable (0.00s)
=== RUN   TestRaceCreateDifferentVariables
--- PASS: TestRaceCreateDifferentVariables (0.00s)
=== RUN   TestRaceReadDifferentVariables
--- PASS: TestRaceReadDifferentVariables (0.00s)
=== RUN   TestRaceSetSameVariable
--- PASS: TestRaceSetSameVariable (0.00s)
=== RUN   TestRaceSetSameVariableNewEnv
--- PASS: TestRaceSetSameVariableNewEnv (0.00s)
=== RUN   TestRaceDefineAndSetSameVariable
--- PASS: TestRaceDefineAndSetSameVariable (0.00s)
=== RUN   TestCopy
--- PASS: TestCopy (0.00s)
=== RUN   TestDeepCopy
--- PASS: TestDeepCopy (0.00s)
=== RUN   TestEnvRef
--- PASS: TestEnvRef (0.00s)
=== RUN   TestArrays
--- PASS: TestArrays (0.01s)
=== RUN   TestArraysAutoAppend
--- PASS: TestArraysAutoAppend (0.00s)
=== RUN   TestMakeArrays
--- PASS: TestMakeArrays (0.00s)
=== RUN   TestArraySlice
--- PASS: TestArraySlice (0.01s)
=== RUN   TestArrayAppendArrays
--- PASS: TestArrayAppendArrays (0.01s)
=== RUN   TestMaps
--- PASS: TestMaps (0.01s)
=== RUN   TestExistenceOfKeyInMaps
--- PASS: TestExistenceOfKeyInMaps (0.00s)
=== RUN   TestDeleteMaps
--- PASS: TestDeleteMaps (0.00s)
=== RUN   TestMakeMaps
--- PASS: TestMakeMaps (0.00s)
=== RUN   TestArraysAndMaps
--- PASS: TestArraysAndMaps (0.00s)
=== RUN   TestMakeArraysAndMaps
--- PASS: TestMakeArraysAndMaps (0.00s)
=== RUN   TestMakeArraysData
--- PASS: TestMakeArraysData (0.00s)
=== RUN   TestMakeMapsData
--- PASS: TestMakeMapsData (0.00s)
=== RUN   TestStructs
--- PASS: TestStructs (0.00s)
=== RUN   TestMakeStructs
--- PASS: TestMakeStructs (0.00s)
=== RUN   TestReturns
--- PASS: TestReturns (0.01s)
=== RUN   TestFunctions
--- PASS: TestFunctions (0.01s)
=== RUN   TestPointerFunctions
--- PASS: TestPointerFunctions (0.00s)
=== RUN   TestVariadicFunctions
--- PASS: TestVariadicFunctions (0.00s)
=== RUN   TestFunctionsInArraysAndMaps
--- PASS: TestFunctionsInArraysAndMaps (0.00s)
=== RUN   TestFunctionConvertions
--- PASS: TestFunctionConvertions (0.01s)
=== RUN   TestVariadicFunctionConvertions
--- PASS: TestVariadicFunctionConvertions (0.00s)
=== RUN   TestLen
--- PASS: TestLen (0.00s)
=== RUN   TestCallFunctionWithVararg
--- PASS: TestCallFunctionWithVararg (0.00s)
=== RUN   TestBasicOperators
--- PASS: TestBasicOperators (0.00s)
=== RUN   TestComparisonOperators
--- PASS: TestComparisonOperators (0.01s)
=== RUN   TestThrows
--- PASS: TestThrows (0.00s)
=== RUN   TestTernaryOperator
--- PASS: TestTernaryOperator (0.00s)
=== RUN   TestNilCoalescingOperator
--- PASS: TestNilCoalescingOperator (0.00s)
=== RUN   TestIf
--- PASS: TestIf (0.00s)
=== RUN   TestSwitch
--- PASS: TestSwitch (0.00s)
=== RUN   TestForLoop
--- PASS: TestForLoop (0.01s)
=== RUN   TestItemInList
--- PASS: TestItemInList (0.00s)
=== RUN   TestOperatorPrecedence
--- PASS: TestOperatorPrecedence (0.00s)
=== RUN   TestTemp
--- PASS: TestTemp (0.00s)
=== RUN   TestNumbers
--- PASS: TestNumbers (0.00s)
=== RUN   TestStrings
--- PASS: TestStrings (0.00s)
=== RUN   TestVar
--- PASS: TestVar (0.00s)
=== RUN   TestModule
--- PASS: TestModule (0.00s)
=== RUN   TestNew
--- PASS: TestNew (0.00s)
=== RUN   TestMake
--- PASS: TestMake (0.00s)
=== RUN   TestMakeType
--- PASS: TestMakeType (0.00s)
=== RUN   TestReferencingAndDereference
--- PASS: TestReferencingAndDereference (0.00s)
=== RUN   TestMakeChan
--- PASS: TestMakeChan (0.00s)
=== RUN   TestChan
--- PASS: TestChan (0.00s)
=== RUN   TestVMDelete
--- PASS: TestVMDelete (0.00s)
=== RUN   TestComment
--- PASS: TestComment (0.00s)
=== RUN   TestCancelWithContext
--- PASS: TestCancelWithContext (0.33s)
=== RUN   TestContextConcurrency
--- PASS: TestContextConcurrency (0.28s)
=== RUN   TestContextFunction
--- PASS: TestContextFunction (0.00s)
=== RUN   TestAssignToInterface
--- PASS: TestAssignToInterface (0.00s)
=== RUN   TestValueEqual
--- PASS: TestValueEqual (0.00s)
=== RUN   Example_vmArrays
--- PASS: Example_vmArrays (0.00s)
=== RUN   Example_vmMaps
--- PASS: Example_vmMaps (0.00s)
=== RUN   Example_vmModules
--- PASS: Example_vmModules (0.00s)
=== RUN   Example_vmFunctions
--- PASS: Example_vmFunctions (0.00s)
=== RUN   Example_vmFunctionsScope
--- PASS: Example_vmFunctionsScope (0.00s)
=== RUN   Example_vmFunctionsOutside
--- PASS: Example_vmFunctionsOutside (0.00s)
=== RUN   Example_vmBasicOperators
--- PASS: Example_vmBasicOperators (0.00s)
=== RUN   Example_vmComparisonOperators
--- PASS: Example_vmComparisonOperators (0.00s)
=== RUN   Example_vmIfOperators
--- PASS: Example_vmIfOperators (0.00s)
=== RUN   Example_vmForLoops
--- PASS: Example_vmForLoops (0.00s)
=== RUN   Example_vmSlices
--- PASS: Example_vmSlices (0.00s)
=== RUN   Example_vmChannels
--- PASS: Example_vmChannels (0.00s)
=== RUN   Example_vmSort
--- PASS: Example_vmSort (0.00s)
=== RUN   Example_vmRegexp
--- PASS: Example_vmRegexp (0.00s)
=== RUN   Example_vmHttp
--- FAIL: Example_vmHttp (0.00s)
got:
listen tcp :8080: bind: address already in use
want:
Hello World :)
=== RUN   ExampleEnv_ExecuteContext
--- PASS: ExampleEnv_ExecuteContext (0.00s)
=== RUN   ExampleEnv_Define
--- PASS: ExampleEnv_Define (0.00s)
=== RUN   ExampleEnv_Dump
--- PASS: ExampleEnv_Dump (0.00s)
=== RUN   Example_vmHelloWorld
--- PASS: Example_vmHelloWorld (0.00s)
=== RUN   Example_vmQuickStart
--- PASS: Example_vmQuickStart (0.00s)
FAIL
coverage: 76.4% of statements in github.com/mattn/anko, github.com/mattn/anko/ast/astutil, github.com/mattn/anko/vm, github.com/mattn/anko/core, github.com/mattn/anko/packages
exit status 1
FAIL	github.com/mattn/anko/vm	0.783s
warning: no packages being tested depend on github.com/mattn/anko
warning: no packages being tested depend on github.com/mattn/anko/ast/astutil
warning: no packages being tested depend on github.com/mattn/anko/packages
=== RUN   TestKeys
--- PASS: TestKeys (0.00s)
=== RUN   TestKindOf
--- PASS: TestKindOf (0.00s)
=== RUN   TestRange
--- PASS: TestRange (0.00s)
=== RUN   TestLoad
--- PASS: TestLoad (0.00s)
=== RUN   TestAnk
```

**Comment by mattn** [comment]
I doubt `core/testdata/chan.ank`.

**Comment by mattn** [comment]
I could fix this.

```diff
diff --git a/vm/vmStmt.go b/vm/vmStmt.go
index ab34199..d567a08 100644
--- a/vm/vmStmt.go
+++ b/vm/vmStmt.go
@@ -4,6 +4,7 @@ import (
        "context"
        "fmt"
        "reflect"
+       "runtime"

        "github.com/mattn/anko/ast"
 )
@@ -468,6 +469,7 @@ func (runInfo *runInfoStruct) runSingleStmt() {
                                        }
                                        break
                                }
+                               runtime.Gosched()
                        }
                        runInfo.rv = nilValue
                        runInfo.env = env
```
@MichaelS11 Could you pleas try this patch?

**Comment by MichaelS11** [comment]
@mattn 

Thank you for your help and finding where it was hanging. Much appreciated! :)

Here is a test of what I think that chan.ank is doing:
```{Script: `a = make(chan int64); go func() { a <- 1; a <- 2; a <- 3 }(); b = []; for i in a { b += i }`, RunOutput: nil, Output: map[string]interface{}{"b": []interface{}{int64(1), int64(2), int64(3)}}},```
It hangs in Go 1.11.5 on Windows

Here is some Go code which I think is the same as what the Anko code is doing. It also hangs but I added context so the timeout is hit.
https://gist.github.com/MichaelS11/96a05f675d0b82793e15465537012fdb

I think the updated Anko code it working correctly as is. The for loop is waiting on the channel to have more data but no more data is coming in.  I think that is the way it should be but please let me know your thoughts.

A couple examples of updated tests that would work:
```{Script: `a = make(chan int64); go func() { a <- 1; a <- 2; a <- 3 }(); b = []; for i in a { b += i; if i > 2 { break } }`, RunOutput: nil, Output: map[string]interface{}{"b": []interface{}{int64(1), int64(2), int64(3)}}},```

```{Script: `a = make(chan int64); go func() { a <- 1; a <- 2; a <- 3; close(a) }(); b = []; for i in a { b += i }`, Input: map[string]interface{}{"close": func(b interface{}) { reflect.ValueOf(b).Close() }}, RunOutput: nil, Output: map[string]interface{}{"b": []interface{}{int64(1), int64(2), int64(3)}}},```

**Comment by MichaelS11** [comment]
@mattn 
Note this Travis build passed as well:
https://travis-ci.org/mattn/anko/builds/487257144?utm_source=github_status&utm_medium=notification

**Comment by MichaelS11** [comment]
I installed Go 1.8.7 on a Linux box and tested over a dozen times, I have not been able to get it to fail once.

@mattn Good to merge

**Comment by mattn** [comment]
Thank you.

**Pull request merged**
