### PR TITLE
0.1.2 - env.NewModule now local. Updated getTypeFromEnv & ModuleStmt

### PR DESCRIPTION
**Pull request by MichaelS11**
getTypeFromEnv now checks parent scope
ModuleStmt now uses NewModule
Added tests for type scope

### CODE REVIEW

**Comment by MichaelS11** [comment]
@mattn Good to merge. Could you make a release before merge and one after?

**Comment by mattn** [comment]
Thank you

**Comment by MichaelS11** [comment]
@mattn Could you make a release?

**Comment by mattn** [comment]
Tagged. Thanks.

**Pull request merged**
