### PR TITLE
0.1.6 Added make struct & TestImport

### PR DESCRIPTION
**Pull request by MichaelS11**
@mattn 
Please review, merge, and add release

### CODE REVIEW

**Comment by MichaelS11** [comment]
@mattn Any thoughts?

**Comment by MichaelS11** [comment]
@mattn Any thoughts?

**Comment by MichaelS11** [comment]
@mattn
Any thoughts?

**Comment by mattn** [comment]
Thank you.

**Comment by MichaelS11** [comment]
@mattn 
Thanks!
Add release?

**Comment by mattn** [comment]
Yes, added tag in few minutes. Thanks

**Comment by MichaelS11** [comment]
Thank you!

**Pull request merged**
