### PR TITLE
Move logic outside of main switch

### PR DESCRIPTION
**Pull request by alaingilbert**
I have a fork of this project.
One of the thing I did was to extract the logic out of the switch.
I find it easier to read and follow the code.
Are you interested by this change ?

### CODE REVIEW

**Comment by MichaelS11** [comment]
Not really seeing how it makes it easier to read or follow the code.

**Comment by alaingilbert** [comment]
Well, having small functions that you can "goto definition" and go back.
Instead of a single function with a thousands lines...

I can see right away what are all the "statements" types that are handled by the `runSingleStmt` just by looking at the switch.
(instead of having to scroll through it, not knowing what is where.

**Comment by MichaelS11** [comment]
Ok, I get what you are saying.

Note that all the statements are in https://github.com/mattn/anko/blob/master/ast/stmt.go already, so not that hard to see what statements are handled.

I am not partiularly for this change.

Plus I am not sure if the commit is clean. At least Github online diff is showing a lot of other diffrences.

**Comment by alaingilbert** [comment]
The main point is code navigation & comprehension.

The git diff is indeed quite ugly
image

But the only thing I did was:
- take the logic in each `case`
- make a function out of it.

But yeah, no big deal, if you don't want this :)

**Comment by MichaelS11** [comment]
Thanks for looking into this.

@mattn has the final say.

**Pull request closed without merging**
