### PR TITLE
Added for in map loop

### PR DESCRIPTION
**Pull request by MichaelS11**
Added to TestForLoop
Added to TestInterrupts

### CODE REVIEW

**Comment by MichaelS11** [comment]
Also would be great to be able to do syntax like `a = {"b": 1}; for key, value in a { //do something }`, just need help with the syntax part.

**Comment by mattn** [comment]
Thanks. Could you please add simple test into `anko/t/06-for.ank`?

**Comment by MichaelS11** [comment]
Welcome.

I was thinking that maybe we could remove the anko/t testing scripts in the future if we could add all the needed tests into the Go tests?

**Comment by MichaelS11** [comment]
Oh yes, would like to move the testing and the examples into Go test examples, so they show up in the docs. 

Like:

https://godoc.org/github.com/mattn/anko/vm#ex-package--VmComparisonOperators

**Comment by mattn** [comment]
Cool. filed new issue. https://github.com/mattn/anko/issues/117

**Comment by MichaelS11** [comment]
In the mean time, could this PR be merged?

**Comment by mattn** [comment]
Thank you

**Pull request merged**
