### PR TITLE
Added tests & removed unneeded

### PR DESCRIPTION
**Pull request by MichaelS11**

### CODE REVIEW

**Comment by MichaelS11** [comment]
@mattn 
Any thoughts on this?

**Comment by mattn** [comment]
Opps. Sorry much. LGTM. Please fix conflicts.

**Comment by mattn** [comment]
I open https://github.com/mattn/anko/compare/pr164?expand=1

**Comment by MichaelS11** [comment]
This is updated, no conflicts.

**Comment by mattn** [comment]
Thanks!

**Pull request merged**
