### PR TITLE
add -c to check syntax

### LINKED ISSUE #129: require dryRun to check syntax
`dryRun` parse the code , and run the `[]ast.Stmt` with `env`, but not really exec.

In simple cases, it is possible to store a set of already defined variables/functions. If there are no variables/functions appearing in the code, there is an error.

### PR DESCRIPTION
**Pull request by mattn**
close #129

### CODE REVIEW

**Comment by MichaelS11** [comment]
@Chyroc 

What do you think of this PR?

**Comment by Chyroc** [comment]
https://github.com/mattn/anko/pull/131/files#diff-24225296f809d09dee7bf63089d526ceR147 run the script?
Maybe people just want to check the grammar and don't want to run this code.
And maybe people want to do grammar checking by calling the interface, not binary.

**Comment by MichaelS11** [comment]
Was wondering what the plan was for this PR? Issue https://github.com/mattn/anko/issues/129 was closed.

**Comment by MichaelS11** [comment]
@mattn 
Any thoughts on what to do with this PR?

**Comment by MichaelS11** [comment]
I find with having it or not having it. I would guess someone would use it but probably not very often.

**Comment by mattn** [comment]
Closing. but if you have create new PR, let's discuss in there.

**Pull request closed without merging**
