### PR TITLE
Changed map key to interface *breaking change*

### PR DESCRIPTION
**Pull request by MichaelS11**
Updated parser to have newline instead of just terms

### CODE REVIEW

**Comment by MichaelS11** [comment]
Suggest creating a new release/version before this.

**Comment by MichaelS11** [comment]
This PR will not give full support for maps of any kind but it is a start. Still more to do.

**Comment by mattn** [comment]
Thanks. I'll look into it in later.

**Comment by MichaelS11** [comment]
@mattn ,

Would you be able to look at this soon?

**Comment by mattn** [comment]
Thank you

**Comment by mattn** [comment]
I tagged v0.0.5 before merging this.

**Pull request merged**
