### PR TITLE
Added ast operators

### PR DESCRIPTION
**Pull request by MichaelS11**
Helps make parser a little easier.

Next up is adding operator precedence testing.

### CODE REVIEW

**Comment by MichaelS11** [comment]
@mattn Good to merge

**Comment by mattn** [comment]
Thanks. Question, what is motivation of this?

**Comment by MichaelS11** [comment]
Enable operator precedence is the main one. I think there are additional benefits like easier to read parser code and smaller switch statements.

**Comment by mattn** [comment]
(I'm okay to merge this)

I wonder how the cost of function call vs switch case, or limit of stacks.

**Comment by MichaelS11** [comment]
I wonder as well, we could probably do some benchmarks.

But really performance was not the goal. When I try to make changes to the parser my head spins. Really trying to split up the parser code to make it easier to manage.

**Comment by mattn** [comment]
>When I try to make changes to the parser my head spins.

lol

Do you want to wait merge until taking benchmark? or merge?

**Comment by MichaelS11** [comment]
:)

Merge please. 

I think the performance difference is small, just think it would be interesting to see.

**Comment by mattn** [comment]
Thanks!

**Comment by mattn** [comment]
FYI, anko is slowly than other implementation. (but I don't mind)

https://github.com/d5/tengo#benchmark

**Pull request merged**
