### PR TITLE
add comment syntax

### PR DESCRIPTION
**Pull request by Chyroc**

### CODE REVIEW

**Comment by Chyroc** [comment]
If you agree, I will add a doc file, and then add the documentation about the annotation.
Anko has a lot of grammar, so it is very difficult to finish all the documents at once. Maybe we can add the documents of the contents we modified in each pr, and then the documents will be more and more abundant.

**Comment by MichaelS11** [comment]
Would rather see example, like:

https://github.com/mattn/anko/blob/master/vm/exampleHelloWorld_test.go
https://github.com/mattn/anko/blob/master/vm/exampleBasicOperators_test.go
etc...

**Comment by MichaelS11** [comment]
Yes, would rather see examples first.

Do we want to remove # as a comment?

As far as the code go, generally looks good, but tricky to see if there might be any parsing errors.

**Comment by Chyroc** [comment]
@mattn Do we want to remove # as a comment?

**Comment by mattn** [comment]
Currently, I don't want to remove.

**Comment by MichaelS11** [comment]
@mattn so go to be merged?

**Comment by Chyroc** [comment]
Is there any idea about this pr?

**Comment by mattn** [comment]
Thanks.

**Pull request merged**
