### PR TITLE
Added string to byte & rune conversion

### PR DESCRIPTION
**Pull request by MichaelS11**

### CODE REVIEW

**Comment by MichaelS11** [comment]
@mattn Good to go

**Comment by mattn** [comment]
Thanks. If the string have two or more letters, this works without errors. hmm...I can't decide which is best yet.

**Comment by MichaelS11** [comment]
Fix makeValue for struct ptr. Added strings.Builder.

@mattn Please merge

**Comment by mattn** [comment]
>If the string have two or more letters, this works without errors. hmm...I can't decide which is best yet.

What do you think? If a string "foo" is passed for argument typed rune, should it work without error?

https://github.com/mattn/anko/pull/313/commits/ea4ba682721774d4ef573487e7be8a9ef096a505#diff-763921223b22a5e0fa21c13a3532ffe9R542

**Comment by MichaelS11** [comment]
I am not sure which is best either. I am fine either way. It is a difficult choice.

**Comment by mattn** [comment]
Could you please add code to make it error? If someone do not want it, let's remove the check.

**Comment by mattn** [comment]
Thanks. I'll merge this after test passed.

**Comment by MichaelS11** [comment]
Welcome :)

**Comment by mattn** [comment]
Thank you

**Pull request merged**
