### PR TITLE
Data races tests and fixes

### PR DESCRIPTION
**Pull request by leonelquinteros**
Here are some new tests to detect data races based on your existent tests. 
Also included several fixes for those. 

More tests in the same style should be written to cover the entire package.

### CODE REVIEW

**Comment by mattn** [comment]
You should make pull-request with working on $GOPATH/src/github.com/mattn/anko not $GOPATH/src/github.com/leonelquinteros/anko :)

**Comment by mattn** [comment]
Okay, I'll rebase your pull-request and re-make this as your's.

**Comment by mattn** [comment]
Merged. https://github.com/mattn/anko/commit/a8c68fa2983e7dd5d3472992b1fbe2f7c44261f0

Thanks.

**Comment by leonelquinteros** [comment]
Sorry, i edited from my fork as i was already using it on my project. 
I'll check now and re-fork to continue using `mattn` import path

**Comment by mattn** [comment]
No prob! :)

**Pull request closed without merging**
