### PR TITLE
Added env.Copy() function to deep copy a scope

### PR DESCRIPTION
**Pull request by c4s4**
I need to copy the state of the VM, so I implemented this Copy() function

### CODE REVIEW

**Comment by MichaelS11** [comment]
What about handling parents or children?

**Comment by c4s4** [comment]
You're right, I have made a new pull request that recursively copies parents. For children, I have no idea how to do it or even if this is a good idea.

**Comment by MichaelS11** [comment]
Should be able to do something very similar for the children.

**Comment by TrueFurby** [comment]
To copy children as well you would need some global map of Envs to loop through and find each that has parent set to the one being copied, since Env only keeps info about it's parent but not vice-versa. 

Altough, I think copying parents should be enough. I someone wants to copy and Env they can still use it on the child directly.

**Comment by MichaelS11** [comment]
Each parent could keep an slice of all it's children, would not have to be global.

If one is going to implement copy, shouldn't it be a full copy? Otherwise call it copyEnvAndParents or something like that.

**Comment by MichaelS11** [comment]
@mattn 

The source repo was deleted, probably can just close this PR.

**Pull request closed without merging**
